FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
LABEL authors="stephen.wille"

ARG DEBIAN_FRONTEND=noninteractive

EXPOSE 5000

RUN apt update && apt install -y \
    wget \
    python3-pip \
    python3.10-venv

RUN pip install ultralytics
RUN pip install flask
RUN pip install python-dotenv
RUN pip install opencv-contrib-python-headless



ENTRYPOINT ["/bin/bash", "./docker-entrypoint.bash"]
